### ISSUE TITLE
Address and quantify any metrics name changes that can break scripts

### ISSUE THREAD

**Issue by drcrallen** [metamx/server-metrics#25]
https://github.com/metamx/server-metrics/pull/21

Any metrics name changes that can break scripts from the above PR need collected and addressed here. If there are backwards incompatible changes the version needs a bump to 0.3.0.

**Comment by leventov** [comment]
@drcrallen 0.2.10 is already released, and it contains "metric name breaking" changes from #20.

**Comment by drcrallen** [comment]
allright, can @leventov or @logarithm get a list of the ones that changed?

**Comment by leventov** [comment]
@drcrallen 
1. `jvm/gc/time` removed, `jvm/gc/cpu` added instead, it reports time in nanoseconds.
2. `jvm/gc/count` reports something different than it used to do, probably the old value is similar to the new with `gcGen=old` dimension filter, but I'm not sure, might be still different.
